language: generic
sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run notes bundle exec rails db:test:prepare
script:
- docker-compose run --rm notes bundle exec rake spec
after_success:
- echo $HEROKU_TOKEN
- echo $MY_SECRET_ENV
- docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
- docker build -t registry.heroku.com/notes/web -f Dockerfile.production .
- docker push registry.heroku.com/notes/web
env:
  global:
  - secure: Fl43mDrXMnpx+EmpWtIlys7QlTQW5rMwVuHDUaWpETCxQktXrjGXB6TBRCCUuyBqsMh3exx1ywSlP8XJSsbtGfKpogLKlDjk/wAZJ9WhUco5rVwIMAVrktoOCxeFPML2vk9b57DBv1tieKXhLh1841oku4n2x7v+9aUrscU13U596oVWEoJiOgmBouRP9kw8yViL14xNFUqwJI0Fjt6hox54HVrRjDlzQFOBOMsDhE0LkGztLQ89iOZgySRua8IZzQU9eVmk9LIq1R18oeu7w0WKFY5j8LJgiTWf1mh1js1jAU12/bHHSsU0+tFpeIiCh3XzGb3PTe48I4omf+lgeVvh/gDPzSZaYKmfIIZ3HQswqPBy4mFUfQPfLky0fxtnRzdlimyxDeUtaweEvW/Ye9jM9TGI7+0OcxzjfEGU1HXU9HWGcvyA83AjLht8zHx+KbfRu70K1BSDKiRdzSel2aToFlMn1j0QXiZ83ENdyIuP29wxE78PsmbtwcgNyFqitFLXa3/VrJsaes2IMpunnJ2Z63JMOGHfrljTX7cKCu92yZgtRnptl+rCFjjQ/HE2Z3s8zvqx49/bITMBcF4PqtqiuVwq+fTca0UdBSw8J65HQElu6jD0SkAEtAAOElINm6bQ4Aanix/7yXaTbj+e8H5KKkOKH8xdDIuZrBEzBds=
  - secure: iHbSFmRnKP6nTmDJKFcFPwBU7Ri7hy8kq9MNd3KIp23mwTJuGqq3IVbuQSWE0j/RWlTxQ+1Y6IAgsX/9uOVUIgtWnUlM9ZO74/hbEgpOUNpcPgIc7XpfLC73rHzZjzFXE8sKXxFqKF00RNyP2Xa9QXlaRPZNpKp90pxZwi5dJm4xCAKOwOWXONiddjO96G3trEqU/92TNY6cYVK687FwC/EgoBNrvI2bToXMIjgsHv6tArQt186iZ5+z7Bm+L3/jk7Pu/ro3j5DfEDIand2yurmQpWFZnu/LiBdXSKgeBuMwk+0YmC2wcxrALGUEU2DqDBvHN9tZyrPIG+y6P+8/eX8eAeGOVCm56w1VuOkZUOMm6Tv3C54qMvg1cYgouTJs5hl07yfZN5/H5LkGfhUgehypYGoQIwn5uRk5bCi42DszG35aX7E2Ho+tVbLkun13VNhdKJ7DRf/yqlBHmYM/5R1pr1mVtm9+UZnowhlbGX16V893XWK/XZvluDHp1MhBimGxBrkOIoP5Raa3H89xLuhA5hslSODxLrHwkJeJofUhJxrSdp6ayeA4JxHjVaoV2oh8pFgcrRjbCuWlVkkEabPEBfe5aXbwNLw+184rdQrvh/gpu9WJigRY9af9nepi0S5maHHlWMJQZHut8D35cu1ROrf9I/w3eLiMxR2qfcQ=
